title: "Asmuie Analytics"
description: "Showcasing my data science projects and web applications"
url: "https://asmuie-analytics.github.io"
baseurl: "/projects"

theme: minima

collections:
  projects:
    output: true
    permalink: /:collection/:name/

plugins:
  - jekyll-feed

main:
  - title: "Home"
    url: https://asmuie-analytics.github.io/
  - title: "Contact Me"
    url: mailto:asmui@uitm.edu.my
  - title: "View Courses"
    url: https://asmuie-analytics.github.io/modules/
