# GitHub Pages + Remote Theme Configuration
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
title: "Data Science Portfolio"
name: "Your Name"
description: "Statistics and Programming for Data Science"
url: "https://asmuie-analytics.github.io" # your GitHub Pages URL
baseurl: "" # leave empty if this is your main site

# Site navigation - THIS IS KEY!
main:
  - title: "Home"
    url: https://asmuie-analytics.github.io/
  - title: "Contact Me"
    url: mailto:asmui@uitm.edu.my
  - title: "View Courses"
    url: https://asmuie-analytics.github.io/modules/

# Author Profile
author:
  name: "Asmui Rahim"
  bio: "Data Science Enthusiast, A Philomath"
  email: "asmui@uitm.edu.my"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/asmuie-analytics"

# Jekyll Plugins (GitHub Pages compatible)
plugins:

# Disable default navigation
masthead_title: " "
breadcrumbs: false

# Or if using Minimal Mistakes, comment out or remove:
# main:
#   - title: "Home"
#     url: /
#   - title: "About"
#     url: /about/
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Other settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/
